version: "3.9"

services:
  db:
    image: postgres:15
    container_name: saas_db
    restart: always
    environment:
      POSTGRES_USER: saas_user
      POSTGRES_PASSWORD: saas_password
      POSTGRES_DB: saas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saas_network

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: saas_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - saas_network

volumes:
  postgres_data:

networks:
  saas_network:
