"""add users_addresses, users_sessions and users_payments_methods table

Revision ID: b115c96841ed
Revises: 27d566d1d433
Create Date: 2025-08-28 15:25:06.733079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b115c96841ed'
down_revision: Union[str, Sequence[str], None] = '27d566d1d433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
